# .rubocop.yml

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"

# Layout
Layout/LineLength:
  Max: 120         

# Metrics
Metrics/MethodLength:
  Max: 15 
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'

# Style
Style/Documentation:
  Enabled: false  
Style/FrozenStringLiteralComment:
  Enabled: true   # ensure using frozen string literals
Style/RedundantSelf:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
