name: CI Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: apace_systems_backend_test
          POSTGRES_HOST: ${{ secrets.DATABASE_HOST }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U $POSTGRES_USER"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.1

      - name: Install dependencies
        run: bundle install

      - name: Wait for the database to be ready
        run: sleep 10

      - name: Set environment variables
        run: |
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> $GITHUB_ENV
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> $GITHUB_ENV
          echo "POSTGRES_DB=apace_systems_backend_test" >> $GITHUB_ENV

      - name: List PostgreSQL databases
        run: |
          PGPASSWORD=$DATABASE_PASSWORD psql -h $DATABASE_HOST -U $DATABASE_USER -d $POSTGRES_DB -c "\l"

      - name: Drop and recreate test database
        run: |
          bin/rails db:drop RAILS_ENV=test || true
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test

      - name: Run tests
        run: RAILS_ENV=test bundle exec rspec